services:
  db:
    image: mongo
    container_name: bkn-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      start_period: 10s
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=bkn-mongo