services:
  db:
    image: mongo
    container_name: bkn-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      start_period: 10s
    profiles: ["dev", "full"]
  backend:
    depends_on:
      - db
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /media/angel/ssdata/bikenance/uploads:/app/uploads
    profiles: ["dev", "full"]
    environment:
      - DB_HOST=bkn-mongo
      - DB_NAME=strava-docker-db
      - UPLOADS_PATH=/app/uploads

  # Start LocalTunnel for obtaining a public address bound to the backend host
  localtunnel:
    image: efrecon/localtunnel
    links:
      - backend
    command:
      --local-host backend --port 8080 --subdomain bikenanceapp
    profiles: ["full"]
