services:
  db:
    image: mongo
    container_name: bkn-mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      start_period: 10s
  backend:
    profiles:
      - full
    depends_on:
      - db
    build:
      context: .
      dockerfile: full.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=bkn-mongo
  backend-local:
    profiles:
      - local
    depends_on:
      - db
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=bkn-mongo
